server:
  port: 8080

spring:
  application:
    name: app-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: app-book
          uri: lb://app-book
          predicates:
            - Path=/app-book/**
          filters:
            - StripPrefix=1
        - id: app-authors
          uri: lb://app-authors
          predicates:
            - Path=/app-authors/**
          filters:
            - StripPrefix=1

    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        health-check-path: /actuator/health
        health-check-interval: 10s

admin:
  client:
    url: http://localhost:8081
    instance:
      service-url: http://localhost:${server.port}
      name: ${spring.application.name}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
